language: java
jdk:
  - oraclejdk8
services:
  - redis-server
branches:
  only:
    - master
addons:
  apt:
    sources:
    - mysql-5.7-trusty
    packages:
    - mysql-server
    - mysql-client
before_install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('root') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo service mysql restart
  - mysql -u root -proot -e 'create database spider'
  - mysql -u root -proot -e 'use spider; source ./spider.sql;'
  - sudo mkdir -p /usr/local/spider/static/img/index/
  - sudo chmod -R a+wrx /usr/local/spider/static/
after_success:
  - mvn jacoco:report coveralls:report -DrepoToken="${COVER_TOKEN}"
